version: '2'
services:
  slack_notify:
    image: vevo/slack-notify:$SLACK_NOTIFY_VERSION
    environment:
      GO_PIPELINE_NAME: $GO_PIPELINE_NAME
      GO_STAGE_NAME: $GO_STAGE_NAME
      GO_JOB_NAME: $GO_JOB_NAME
      GO_PIPELINE_COUNTER: $GO_PIPELINE_COUNTER
      GO_TO_REVISION: $GO_TO_REVISION
    volumes:
      - .:/repos

  success:
    extends:
      service: slack_notify
    environment:
      SUCCESS: "true"
      SLACK_CHANNELS: $SLACK_CHANNELS_SUCCESS

  failure:
    extends:
      service: slack_notify
    environment:
      SUCCESS: "false"
      SLACK_CHANNELS: $SLACK_CHANNELS_FAILURE